export const TODOS = [
  {
    id: 1,
    title: "Do something nice for someone you care about",
    completed: false,
    userId: 152,
  },
  {
    id: 2,
    title: "Memorize a poem",
    completed: true,
    userId: 13,
  },
  {
    id: 3,
    title: "Watch a classic movie",
    completed: true,
    userId: 68,
  },
  {
    id: 4,
    title: "Watch a documentary",
    completed: false,
    userId: 84,
  },
  {
    id: 5,
    title: "Invest in cryptocurrency",
    completed: false,
    userId: 163,
  },
  {
    id: 6,
    title: "Contribute code or a monetary donation to an open-source software project",
    completed: false,
    userId: 69,
  },
  {
    id: 7,
    title: "Solve a Rubik's cube",
    completed: true,
    userId: 76,
  },
  {
    id: 8,
    title: "Bake pastries for yourself and neighbor",
    completed: true,
    userId: 198,
  },
  {
    id: 9,
    title: "Go see a Broadway production",
    completed: false,
    userId: 7,
  },
  {
    id: 10,
    title: "Write a thank you letter to an influential person in your life",
    completed: true,
    userId: 9,
  },
  {
    id: 11,
    title: "Invite some friends over for a game night",
    completed: false,
    userId: 104,
  },
  {
    id: 12,
    title: "Have a football scrimmage with some friends",
    completed: false,
    userId: 32,
  },
  {
    id: 13,
    title: "Text a friend you haven't talked to in a long time",
    completed: true,
    userId: 2,
  },
  {
    id: 14,
    title: "Organize pantry",
    completed: false,
    userId: 46,
  },
  {
    id: 15,
    title: "Buy a new house decoration",
    completed: true,
    userId: 105,
  },
  {
    id: 16,
    title: "Plan a vacation you've always wanted to take",
    completed: true,
    userId: 162,
  },
  {
    id: 17,
    title: "Clean out car",
    completed: false,
    userId: 71,
  },
  {
    id: 18,
    title: "Draw and color a Mandala",
    completed: true,
    userId: 6,
  },
  {
    id: 19,
    title: "Create a cookbook with favorite recipes",
    completed: true,
    userId: 53,
  },
  {
    id: 20,
    title: "Bake a pie with some friends",
    completed: false,
    userId: 162,
  },
  {
    id: 21,
    title: "Create a compost pile",
    completed: false,
    userId: 13,
  },
  {
    id: 22,
    title: "Take a hike at a local park",
    completed: true,
    userId: 37,
  },
  {
    id: 23,
    title: "Take a class at local community center that interests you",
    completed: true,
    userId: 65,
  },
  {
    id: 24,
    title: "Research a topic interested in",
    completed: true,
    userId: 130,
  },
  {
    id: 25,
    title: "Plan a trip to another country",
    completed: false,
    userId: 140,
  },
  {
    id: 26,
    title: "Improve touch typing",
    completed: false,
    userId: 178,
  },
  {
    id: 27,
    title: "Learn Express.js",
    completed: false,
    userId: 194,
  },
  {
    id: 28,
    title: "Learn calligraphy",
    completed: false,
    userId: 80,
  },
  {
    id: 29,
    title: "Have a photo session with some friends",
    completed: true,
    userId: 91,
  },
  {
    id: 30,
    title: "Go to the gym",
    completed: true,
    userId: 142,
  },
];
